### ISSUE TITLE
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/cuda/Module.cpp:88

### ISSUE THREAD

**Issue by laocaibcc** [pyinstaller/pyinstaller#2956]
The error occurred when running the application after it was successfully built. Detailed informaiton is listed below.
It runs successfully in the machine where it was built. But it went wrong when I copy it to another machine.
Actually, I found a interesting thing. In the /dist/main/ directory, torch.cuda.is_available is **False** while it is **True** outside this directory. That means cuda is unavailable only in this directory. Maybe this is related to hardware. GPU is needed for my program.

Python 2.7
PyInstaller 3.3
Ubuntu 16.04  64bits
torch 0.2.0

Detailed information
`THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=88 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "main.py", line 44, in <module>
  File "torch/cuda/__init__.py", line 202, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/cuda/Module.cpp:88
[8461] Failed to execute script main`

**Comment by drazellan** [comment]
Hello, i have the same problem with pyinstaller and pytorch/cuda. It works on the machine where it was built but don't on another machine even with cuda and pytorch installed on it.
I don't understand what you said "In the /dist/main/ directory, torch.cuda.is_available is False while it is True outside this directory." coud you explain it?
Thanks

**Comment by caifeiyue** [comment]
Yeah.  It means that when I use the following command, I got **False** in the built directory `/dist/main`, but got **True** outside the directory.

`python` # enter python environment first(ipython also okay), then check cuda device
`import torch`
`torch.cuda.is_available`

**Comment by technopremium** [comment]
Thanks, this solved my problem as well
